services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Calculator
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red_calculadora_nerio

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: calculator_app
    ports:
      - "5015:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - red_calculadora_nerio

volumes:
  postgres_data:

networks:
  red_calculadora_nerio:
    driver: bridge
    ipam:
      config:
        - subnet: 10.240.5.0/24
